#!/usr/bin/python3

import psutil as ps
from enum import Enum


class Level(Enum):
    NORMAL = 1
    WARNING = 2
    ALERT = 3


# Setting

UPDATE_INTERVAL = 10

THRESHOLDS = {
    85: Level.ALERT,
    50: Level.WARNING
}

ICON = "<span font='FontAwesome 10'>\uf2db</span>"
TMPLS = {
    Level.NORMAL: ICON + " {:.1f}%",
    Level.WARNING: ICON + " <span foreground='#f27835'>{:.1f}%</span>",
    Level.ALERT: ICON + " <span foreground='#fc4138'>{:.1f}%</span>"
}


# Get information

def get_raw():
    """Get the current CPU usage and level."""
    percent = ps.cpu_percent(interval=UPDATE_INTERVAL)

    for threshold, level in THRESHOLDS.items():
        if percent > threshold:
            return [level, percent]
    return [Level.NORMAL, percent]


# Get formatted string

def get_output():
    """Get a string for CPU usage."""
    level, percent = get_raw()
    tmpl = TMPLS.get(level)
    return tmpl.format(percent)


# Print

if __name__ == "__main__":
    try:
        while True:
            print(get_output(), flush=True)
    except KeyboardInterrupt:
        pass
