#!/usr/bin/python3

import psutil as ps
from enum import Enum


class Level(Enum):
    NORMAL = 1
    WARNING = 2
    ALERT = 3


# Setting

MONITOR_PATH = "/home/"

THRESHOLDS = {
    5: Level.WARNING,
    1: Level.ALERT
}

ICON = "<span font='FontAwesome 10'>\uf1c0</span>"
TMPLS = {
    Level.NORMAL: ICON + " {:.1f}G",
    Level.WARNING: ICON + " <span foreground='#f27835'>{:.1f}G</span>",
    Level.ALERT: ICON + " <span foreground='#fc4138'>{:.1f}G</span>"
}


# Helper

def convert_bytes(num):
    """Convert bytes to gigabytes."""
    return num / 1024 ** 3


# Get information

def get_raw():
    """Get the available disk space and level of usage."""
    info = ps.disk_usage(MONITOR_PATH)
    avail = convert_bytes(info.free)

    for threshold, level in THRESHOLDS.items():
        if avail < threshold:
            return [level, avail]
    return [Level.NORMAL, avail]


# Get formatted string

def get_output():
    """Get a string for disk usage."""
    level, avail = get_raw()
    tmpl = TMPLS.get(level)
    return tmpl.format(avail)


# Print

if __name__ == "__main__":
    try:
        print(get_output())
    except KeyboardInterrupt:
        pass
