#!/usr/bin/python3

import datetime


# Setting

TMPL = "%Y-%m-%d %a %H:%M"


# Get formatted string

def get_output():
    """Get current time and date."""
    return datetime.datetime.now().strftime(TMPL)


# Print

if __name__ == "__main__":
    try:
        print(get_output())
    except KeyboardInterrupt:
        pass
