#!/usr/bin/python3

import urllib.request as r
import socket
import time

# Setting

MAX_RETRY = 5
RETRY_INTERVAL = 30
LOCATION = "Pittsburgh"
ELEMENTS = ["%c", "%t", "%h"]
SEP = ":"
REQ = r.Request("https://wttr.in/{}?m&format={}".format(LOCATION,
                                                        SEP.join(ELEMENTS)),
                headers={"User-Agent": "python-requests/2.25.1"})
TMPL = "<span font='Noto Color Emoji 10'>{}</span> {} {}"


# Core

def get_raw():
    """Get weather information."""
    num_retry = 0
    while num_retry < MAX_RETRY:
        try:
            with r.urlopen(REQ, timeout=3) as f:
                line = f.readline().decode("utf-8")
            results = line.split(SEP)
            # NOTE: List slices do not perform bound check, so here explicit
            # indexing is used.
            return [results[idx].strip() for idx in range(len(ELEMENTS))]
        # NOTE: The response may not always be in the desired format. In that
        # case nothing should be returned.
        except IndexError:
            return None
        # NOTE: Occasionally the socket.timeout exception is not handled by
        # urllib, so to be safer we catch both.
        except (r.URLError, socket.timeout):
            pass

        num_retry += 1
        time.sleep(RETRY_INTERVAL)
    return None


def get_output():
    """Get a string for weather."""
    weather = get_raw()
    if weather is None:
        return None
    return TMPL.format(*weather)


# Print

if __name__ == "__main__":
    try:
        time.sleep(10)
        output = get_output()
        if output:
            print(output)
    except KeyboardInterrupt:
        pass
