#!/usr/bin/python3

import urllib.request as r
import socket
import time

# Settings

## Request
## NOTE: Here : is a separator between elements
REQ = r.Request("https://wttr.in/Pittsburgh?m&format=%c:%t:%h",
                headers={"User=Agent": "python-requests"})

## Max number of retries
MAX_RETRY = 5

## Interval between retries
RETRY_INTERVAL = 30

## Template
TMPL = "<span font='Noto Color Emoji 10'>{}</span> {} {}"


# Get information

def get_raw():
    """Get weather information."""
    num_retry = 0

    while num_retry <= MAX_RETRY:
        try:
            res = r.urlopen(REQ, timeout=3)
            lines = res.read().decode().splitlines()
            # The response is possible to be empty
            if len(lines) > 0:
                return lines[0].split(":")
        # NOTE: Occasionally the socket.timeout exception is not handled by
        # urllib, so to be safer we catch both
        except (r.URLError, socket.timeout):
            pass

        # Retry when something is wrong
        num_retry += 1
        time.sleep(RETRY_INTERVAL)

    return None


# Get formatted string

def get_output():
    """Get a string for weather."""
    weather = get_raw()
    if weather is None:
        return None

    return TMPL.format(*weather)


# Print

if __name__ == "__main__":
    try:
        # Rest for a while
        time.sleep(10)
        output = get_output()
        if output:
            print(output)
    except KeyboardInterrupt:
        pass
