#!/bin/sh

# Logging
logfile="$HOME/.local/share/sx/session.log"
[ -e "$logfile" ] && mv -f "$logfile" "$logfile.old"
exec >"$logfile" 2>&1
unset logfile

# Default application
export TERMINAL='urxvt'
export BROWSER='xdg-open'

# Input method
export GTK_IM_MODULE='fcitx'
export QT_IM_MODULE='fcitx'
export XMODIFIERS='@im=fcitx'

# QT theme
export QT_QPA_PLATFORMTHEME='qt5ct'

# Load resource file
[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

# Source provided scripts
if [ -d '/etc/X11/xinit/xinitrc.d' ]; then
  for script in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$script" ] && [ -f "$script" ] && . "$script"
  done
  unset script
fi

# Start window manager
exec i3
